In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as  sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import Ridge,Lasso
from sklearn.metrics import r2_score,mean_squared_error
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('housePredictionDataSet.csv',delim_whitespace=True)
data

0.00632  18.00  2.310  0  0.5380  6.5750  65.20  4.0900  1  296.0  15.30  \
0    0.02731    0.0   7.07  0   0.469   6.421   78.9  4.9671  2  242.0   17.8   
1    0.02729    0.0   7.07  0   0.469   7.185   61.1  4.9671  2  242.0   17.8   
2    0.03237    0.0   2.18  0   0.458   6.998   45.8  6.0622  3  222.0   18.7   
3    0.06905    0.0   2.18  0   0.458   7.147   54.2  6.0622  3  222.0   18.7   
4    0.02985    0.0   2.18  0   0.458   6.430   58.7  6.0622  3  222.0   18.7   
..       ...    ...    ... ..     ...     ...    ...     ... ..    ...    ...   
500  0.06263    0.0  11.93  0   0.573   6.593   69.1  2.4786  1  273.0   21.0   
501  0.04527    0.0  11.93  0   0.573   6.120   76.7  2.2875  1  273.0   21.0   
502  0.06076    0.0  11.93  0   0.573   6.976   91.0  2.1675  1  273.0   21.0   
503  0.10959    0.0  11.93  0   0.573   6.794   89.3  2.3889  1  273.0   21.0   
504  0.04741    0.0  11.93  0   0.573   6.030   80.8  2.5050  1  273.0   21.0   

     396.90  4.98  24.00  
0    396.90  9.14   21.6  
1    392.83  4.03   34.7  
2    394.63  2.94   33.4  
3    396.90  5.33   36.2  
4    394.12  5.21   28.7  
..      ...   ...    ...  
500  391.99  9.67   22.4  
501  396.90  9.08   20.6  
502  396.90  5.64   23.9  
503  393.45  6.48   22.0  
504  396.90  7.88   11.9  

[505 rows x 14 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   0.00632  505 non-null    float64
 1   18.00    505 non-null    float64
 2   2.310    505 non-null    float64
 3   0        505 non-null    int64  
 4   0.5380   505 non-null    float64
 5   6.5750   505 non-null    float64
 6   65.20    505 non-null    float64
 7   4.0900   505 non-null    float64
 8   1        505 non-null    int64  
 9   296.0    505 non-null    float64
 10  15.30    505 non-null    float64
 11  396.90   505 non-null    float64
 12  4.98     505 non-null    float64
 13  24.00    505 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.4 KB


In [4]:
data.columns = ["CRIM","ZN","INDUS","CHAS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT","MEDV"]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     505 non-null    float64
 1   ZN       505 non-null    float64
 2   INDUS    505 non-null    float64
 3   CHAS     505 non-null    int64  
 4   NOX      505 non-null    float64
 5   RM       505 non-null    float64
 6   AGE      505 non-null    float64
 7   DIS      505 non-null    float64
 8   RAD      505 non-null    int64  
 9   TAX      505 non-null    float64
 10  PTRATIO  505 non-null    float64
 11  B        505 non-null    float64
 12  LSTAT    505 non-null    float64
 13  MEDV     505 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.4 KB


In [6]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  505.000000  505.000000  505.000000  505.000000  505.000000  505.000000   
mean     3.620667   11.350495   11.154257    0.069307    0.554728    6.284059   
std      8.608572   23.343704    6.855868    0.254227    0.115990    0.703195   
min      0.009060    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082210    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.259150    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.678220   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  505.000000  505.000000  505.000000  505.000000  505.000000  505.000000   
mean    68.581584    3.794459    9.566337  408.459406   18.461782  356.594376   
std     28.176371    2.107757    8.707553  168.629992    2.162520   91.367787   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.000000    2.100000    4.000000  279.000000   17.400000  375.330000   
50%     77.700000    3.199200    5.000000  330.000000   19.100000  391.430000   
75%     94.100000    5.211900   24.000000  666.000000   20.200000  396.210000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  505.000000  505.000000  
mean    12.668257   22.529901  
std      7.139950    9.205991  
min      1.730000    5.000000  
25%      7.010000   17.000000  
50%     11.380000   21.200000  
75%     16.960000   25.000000  
max     37.970000   50.000000

In [7]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [8]:
x = data.iloc[:,:-1]
y= data.iloc[:,-1]
x

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.02731  0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
1    0.02729  0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
2    0.03237  0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
3    0.06905  0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
4    0.02985  0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222.0   
..       ...  ...    ...   ...    ...    ...   ...     ...  ...    ...   
500  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
501  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
502  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
503  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
504  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  
0       17.8  396.90   9.14  
1       17.8  392.83   4.03  
2       18.7  394.63   2.94  
3       18.7  396.90   5.33  
4       18.7  394.12   5.21  
..       ...     ...    ...  
500     21.0  391.99   9.67  
501     21.0  396.90   9.08  
502     21.0  396.90   5.64  
503     21.0  393.45   6.48  
504     21.0  396.90   7.88  

[505 rows x 13 columns]

In [9]:
y

0      21.6
1      34.7
2      33.4
3      36.2
4      28.7
       ... 
500    22.4
501    20.6
502    23.9
503    22.0
504    11.9
Name: MEDV, Length: 505, dtype: float64

In [10]:
x_scaler = StandardScaler()
x_scaler = x_scaler.fit_transform(x)


In [11]:
x_train,x_test,y_train,y_test = train_test_split(x_scaler,y,test_size = 0.2,random_state=42)
x_train

array([[-0.40919982, -0.48671582,  0.24466692, ...,  0.11026674,
         0.18696464, -0.09789281],
       [ 0.73788847, -0.48671582,  1.01411366, ...,  0.80458972,
         0.33015471,  0.8666548 ],
       [-0.2984562 , -0.48671582, -0.44009688, ...,  1.17489532,
         0.33146939, -0.85354856],
       ...,
       [-0.41763466,  1.22850742, -1.44607185, ...,  0.57314873,
         0.36433627, -0.95028372],
       [ 1.25582301, -0.48671582,  1.01411366, ...,  0.80458972,
        -3.60554542,  0.7544981 ],
       [-0.39639988, -0.48671582, -0.37877475, ...,  1.12860712,
         0.41495128,  0.10819512]])

In [12]:
x_test

array([[-0.41118353, -0.48671582, -1.03725764, ..., -0.86178544,
         0.4013663 , -0.42454919],
       [-0.40983819,  1.22850742, -0.69268566, ..., -0.39890345,
         0.44157346, -1.35825371],
       [-0.40871029, -0.48671582,  2.42160259, ...,  0.75830153,
         0.36718474,  0.75730202],
       ...,
       [-0.40826261, -0.48671582,  0.11326235, ...,  1.17489532,
         0.40377654, -0.86756815],
       [-0.41378351,  1.22850742, -1.44607185, ...,  0.57314873,
         0.44157346, -0.93766609],
       [-0.4126905 , -0.48671582, -0.9730154 , ...,  0.01769034,
         0.42240111, -0.59278424]])

In [13]:
y_train

75     20.0
442    15.4
15     23.1
325    23.0
388    11.5
       ... 
106    20.4
270    25.2
348    26.6
435     9.6
102    19.3
Name: MEDV, Length: 404, dtype: float64

In [14]:
y_test

173    22.6
274    32.0
490    13.6
72     23.4
305    33.4
       ... 
331    19.4
411    17.9
503    22.0
349    22.9
86     22.2
Name: MEDV, Length: 101, dtype: float64

In [15]:
ridge = Ridge()

In [16]:
param_grid = {
    "alpha": [0.001, 0.01, 0.1, 1, 10, 50, 100, 200, 500]
}

model = GridSearchCV(estimator=ridge,param_grid=param_grid,cv=5,scoring='r2',n_jobs=-1)

In [22]:
model = model.best_estimator_

In [23]:
model.fit(x_train,y_train)

Ridge(alpha=10)

In [24]:
y_pred = model.predict(x_test)
y_pred

array([26.59353333, 33.43250943, 15.24566822, 24.01133511, 35.27080235,
       23.62510248, 11.26268252,  3.9763208 , 23.0128662 , 20.93264455,
       29.83506047, 19.65757917, 27.3542757 , 22.63720414, 19.5951134 ,
       25.97369565, 21.85725456,  7.97707671, 36.21643295, 17.91615101,
       28.324375  , 35.01662648, 18.61703008, 24.00449515, 18.16449319,
       11.54179504, 28.46165047, 21.65599448, 16.80390053, 19.49479167,
       29.44608194, 14.89010204, 26.12180327, 19.58608296, 16.9563398 ,
       23.10512043, 29.35174443, 20.16422231, 16.82776706, 25.69009587,
       14.18670351, 18.9075199 , 22.4839813 , 21.06203797, 27.91031817,
       30.8124587 , 13.81400715, 21.63869179, 20.22659364, 25.56694481,
       20.97695831, 40.53088184, 14.24018934, 19.58257377, 25.174869  ,
       22.33223863, 19.1256085 , 33.43781817, 28.18786879, 20.17986271,
       24.27132393, 24.73218824, 24.41272063, 18.6512694 , 16.29996115,
       22.44615062, 20.6745718 , 24.92828937, 33.48953278, 11.90

In [25]:
r2_score(y_pred,y_test)

0.6484371277585472

In [26]:
mean_squared_error(y_pred,y_test)

19.187393235983965