In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('iris.csv')
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

since their is no null value in this data set

In [5]:
Encoder = LabelEncoder()

In [6]:
data['species'] = Encoder.fit_transform(data['species'])
data['species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [7]:
data

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [8]:
x= data.iloc[:,:-1]
y = data.iloc[:,-1]

In [9]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [12]:
scaler = MinMaxScaler()
x_normal = scaler.fit_transform(x)
x_normal

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x_normal,y,test_size = 0.2,random_state=42)
x_train

array([[0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.58333333, 0.45833333,

In [15]:
x_test

array([[0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.36111111, 0.20833333,

In [16]:
y_train

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: species, Length: 120, dtype: int64

In [17]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: species, dtype: int64